#!/usr/bin/env bash
set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly EXPECTED_INFO_PLIST="$REPO_ROOT/App/AlpenLedgerApp/Info.plist"
readonly EXPECTED_APP_NAME="AlpenLedgerApp"

usage() {
    cat <<'USAGE'
Usage: scripts/verify-release-artifact.sh path/to/AlpenLedgerApp.zip

Verifies a packaged release ZIP after Developer ID signing, notarization, and
stapling. The ZIP must contain AlpenLedgerApp.app built from the current
checkout/tag and must have an adjacent .sha256 sidecar generated by
scripts/package-release.sh.
USAGE
}

failures=()

record_failure() {
    failures+=("$1")
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        record_failure "Missing required command: $1"
    fi
}

while (($#)); do
    case "$1" in
        -h | --help)
            usage
            exit 0
            ;;
        -*)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
        *)
            break
            ;;
    esac
done

if [[ $# -ne 1 ]]; then
    usage >&2
    exit 2
fi

readonly ARTIFACT_PATH="$1"
readonly ARTIFACT_BASENAME="${ARTIFACT_PATH##*/}"
readonly CHECKSUM_PATH="${ARTIFACT_PATH}.sha256"

require_command codesign
require_command ditto
require_command find
require_command plutil
require_command shasum
require_command spctl
require_command xcrun

if [[ ! -f "$EXPECTED_INFO_PLIST" ]]; then
    record_failure "Missing expected app Info.plist: $EXPECTED_INFO_PLIST"
fi

if [[ ! -f "$ARTIFACT_PATH" ]]; then
    record_failure "Release artifact does not exist: $ARTIFACT_PATH"
elif [[ "$ARTIFACT_PATH" != *.zip ]]; then
    record_failure "Release artifact must be a .zip file so the final payload can be checksummed."
fi

artifact_checksum=""
if [[ ! -f "$CHECKSUM_PATH" ]]; then
    record_failure "Release checksum sidecar does not exist: $CHECKSUM_PATH"
elif [[ -f "$ARTIFACT_PATH" ]]; then
    artifact_checksum="$(shasum -a 256 "$ARTIFACT_PATH" | awk '{ print $1 }')"
    sidecar_line_count="$(awk 'END { print NR }' "$CHECKSUM_PATH")"
    sidecar_field_count="$(awk 'NR == 1 { print NF }' "$CHECKSUM_PATH")"
    sidecar_checksum="$(awk 'NR == 1 { print $1 }' "$CHECKSUM_PATH")"
    sidecar_filename="$(awk 'NR == 1 { print $2 }' "$CHECKSUM_PATH")"

    if [[ "$sidecar_line_count" != "1" || "$sidecar_field_count" != "2" ]]; then
        record_failure "Release checksum sidecar must contain exactly one '<sha256>  <filename>' line."
    fi
    if [[ ! "$sidecar_checksum" =~ ^[[:xdigit:]]{64}$ ]]; then
        record_failure "Release checksum sidecar must start with a 64-character SHA-256 digest."
    elif [[ "$sidecar_checksum" != "$artifact_checksum" ]]; then
        record_failure "Checksum sidecar digest must match the release ZIP."
    fi
    if [[ "$sidecar_filename" != "$ARTIFACT_BASENAME" ]]; then
        record_failure "Checksum sidecar filename must be $ARTIFACT_BASENAME; found $sidecar_filename."
    fi
fi

if [[ ${#failures[@]} -gt 0 ]]; then
    echo "Release artifact verification failed:" >&2
    for failure in "${failures[@]}"; do
        echo "  - $failure" >&2
    done
    exit 1
fi

tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/alpenledger-release-artifact.XXXXXX")"
cleanup() {
    rm -rf "$tmpdir"
}
trap cleanup EXIT

ditto -x -k "$ARTIFACT_PATH" "$tmpdir"

app_candidates=()
while IFS= read -r candidate; do
    app_candidates+=("$candidate")
done < <(find "$tmpdir" -type d -name "${EXPECTED_APP_NAME}.app" -prune -print)

if [[ ${#app_candidates[@]} -eq 0 ]]; then
    record_failure "Release ZIP must contain ${EXPECTED_APP_NAME}.app."
elif [[ ${#app_candidates[@]} -gt 1 ]]; then
    record_failure "Release ZIP must contain exactly one ${EXPECTED_APP_NAME}.app."
else
    app_path="${app_candidates[0]}"
    app_info_plist="$app_path/Contents/Info.plist"

    expected_bundle_id="$(plutil -extract CFBundleIdentifier raw "$EXPECTED_INFO_PLIST" 2>/dev/null || true)"
    expected_marketing_version="$(plutil -extract CFBundleShortVersionString raw "$EXPECTED_INFO_PLIST" 2>/dev/null || true)"
    expected_build_version="$(plutil -extract CFBundleVersion raw "$EXPECTED_INFO_PLIST" 2>/dev/null || true)"

    actual_bundle_id="$(plutil -extract CFBundleIdentifier raw "$app_info_plist" 2>/dev/null || true)"
    actual_marketing_version="$(plutil -extract CFBundleShortVersionString raw "$app_info_plist" 2>/dev/null || true)"
    actual_build_version="$(plutil -extract CFBundleVersion raw "$app_info_plist" 2>/dev/null || true)"

    if [[ "$actual_bundle_id" != "$expected_bundle_id" ]]; then
        record_failure "Artifact bundle identifier must be $expected_bundle_id; found $actual_bundle_id."
    fi

    if [[ "$actual_marketing_version" != "$expected_marketing_version" ]]; then
        record_failure "Artifact marketing version must be $expected_marketing_version; found $actual_marketing_version."
    fi

    if [[ "$actual_build_version" != "$expected_build_version" ]]; then
        record_failure "Artifact build version must be $expected_build_version; found $actual_build_version."
    fi

    if ! codesign --verify --deep --strict --verbose=2 "$app_path" >/dev/null 2>&1; then
        record_failure "codesign verification failed for ${EXPECTED_APP_NAME}.app."
    fi

    codesign_details="$(codesign --display --verbose=4 "$app_path" 2>&1 || true)"

    if [[ -n "${ALPENLEDGER_DEVELOPER_ID_APPLICATION:-}" ]]; then
        if ! grep -F "Authority=${ALPENLEDGER_DEVELOPER_ID_APPLICATION}" <<<"$codesign_details" >/dev/null; then
            record_failure "Artifact is not signed with ALPENLEDGER_DEVELOPER_ID_APPLICATION."
        fi
    elif ! grep -E '^Authority=Developer ID Application:' <<<"$codesign_details" >/dev/null; then
        record_failure "Artifact must be signed with a Developer ID Application certificate."
    fi

    team_identifier="$(awk -F= '/^TeamIdentifier=/{ print $2; exit }' <<<"$codesign_details")"
    if [[ -z "$team_identifier" || "$team_identifier" == "not set" ]]; then
        record_failure "Artifact signature must include a TeamIdentifier."
    elif [[ -n "${ALPENLEDGER_RELEASE_TEAM_ID:-}" && "$team_identifier" != "$ALPENLEDGER_RELEASE_TEAM_ID" ]]; then
        record_failure "Artifact TeamIdentifier must match ALPENLEDGER_RELEASE_TEAM_ID."
    fi

    if ! grep -Eq 'flags=.*runtime|^Runtime Version=' <<<"$codesign_details"; then
        record_failure "Artifact signature must include hardened runtime."
    fi

    if ! grep -Eq '^Timestamp=' <<<"$codesign_details"; then
        record_failure "Artifact signature must include a trusted timestamp."
    fi

    if ! spctl -a -vv -t exec "$app_path" >/dev/null 2>&1; then
        record_failure "Gatekeeper assessment failed for ${EXPECTED_APP_NAME}.app."
    fi

    if ! xcrun stapler validate "$app_path" >/dev/null 2>&1; then
        record_failure "Stapled notarization ticket validation failed for ${EXPECTED_APP_NAME}.app."
    fi
fi

if [[ ${#failures[@]} -gt 0 ]]; then
    echo "Release artifact verification failed:" >&2
    for failure in "${failures[@]}"; do
        echo "  - $failure" >&2
    done
    exit 1
fi

echo "Release artifact verification passed."
echo "Artifact: $ARTIFACT_PATH"
echo "Checksum: $CHECKSUM_PATH"
echo "Bundle: $actual_bundle_id"
echo "Version: $actual_marketing_version ($actual_build_version)"
echo "SHA-256: $artifact_checksum"
